remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

url: https://pygera.github.io/
baseurl: Pummarola/

title: Pummarola
description: A simple pomodoro timer for iOS

show_downloads: true

